# 导航栏
menu:                      # 导航栏上的链接
  首页: /
  文章: /archives
  关于: /about
rss: /atom.xml

home:
  style: default           # default, detail

favicon: /images/favicon.ico                  # Favicon 文件路径，相对于 /source 目录（若你的 Favicon 文件位于 /source/favicon.png 则填写 "/favicon.png"）
brand: /images/brand.png

# 横幅图片
banner:
  enable: true                  # 是否显示横幅图片
  url: /images/banner/banner.jpg                          # 横幅图片文件路径，相对于 /source 目录，也可填写网络图片 URL
  position: center               # 决定图片将如何被裁剪，对应 CSS 中的 "object-position" 属性
  onAllPages: true               # 在所有页面上显示横幅，而不是只在首页显示

# 外观
hue: 250                         # 主题色调 (例如：红: 0，橙: 60，蓝：260，紫：300，粉：345)
                                 # 可访问 `saicaca.github.io/vivia-preview` 预览颜色设置

# 个人信息
avatar: /images/avatar.jpg                        # 头像图片文件路径，相对于 /source 目录
author: 逗逗
subtitle: 采百家花，酿自己蜜
qq: /images/contact/QQ.jpg
weixin: /images/contact/weixin.jpg
links:
  - name: QQ
    icon: fa-brands fa-qq      # 访问 https://fontawesome.com/search 获取图标代码
    url: 516289267@qq.com
  - name: 微信
    icon: fa-brands fa-weixin
    url: 15121038211
#  - name: 手机号
#    icon: fa-solid fa-phone
#    url: 15121038211

# 侧边栏
sidebar:
  widgets:                 # 需要启用的组件 (profile, category, tag, archive, recent_posts)
    normal:                # 随页面滚动的组件
      - profile
    sticky:                # 固定在页面顶部的组件
      - category
      - tag
      - recent_posts
      - archive

# 侧边栏组件设置
archive_type: 'monthly'
recent_posts_limits: 5
categories:
  max_depth: 2             # 分类组件中显示的最大目录深度 (留空为不限制)

# 第三方评论系统
comment:
  valine:
    enable: false          # 是否启用 Valine 评论系统
    appId: 
    appKey: 
    placeholder: 留点什么吧~
    pageSize: 10
    highlight: true
    serverURLs: 
    # 可在此添加其他 Valine 支持的配置项
    # 详见 https://valine.js.org/configuration.html
  twikoo:
    enable: false           # 是否启用 Twikoo 评论系统
    envID:
    region:
    path: location.pathname
    lang:
    # 详见 https://github.com/imaegoo/twikoo
  waline:
    enable: false          # 是否启用 Waline 评论系统
    serverURL: 

#Analytics
gauges_analytics: true
google_analytics: true #UA-xxxxxx
baidu_analytics: true # ddxxxxxxxxxxxxxxxxx In the https://hm.baidu.com/hm.js? Afterwards
